<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Denim</name>
   <tag></tag>
   <elementGuidId>d7f550a6-8a14-4757-a08f-394209499ed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-344']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-344 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9db177fc-a527-4840-a40a-9d43e9986916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/product-category/denim/</value>
      <webElementGuid>aa48b6ab-e2ec-4dea-9853-567677b5a3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denim</value>
      <webElementGuid>1214bbfe-7684-4442-8a49-4e29d80456cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-344&quot;)/a[1]</value>
      <webElementGuid>caf61d7d-d2bf-474a-b6dc-fcbfc80fcd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>196cc052-36fb-47b5-beb6-5ba68c367e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-344']/a</value>
      <webElementGuid>e55af6dd-a4e9-43d3-b397-02d009b27801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Denim')]</value>
      <webElementGuid>c22d4d46-b61c-4054-a733-09fb838a6ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men'])[2]/following::a[1]</value>
      <webElementGuid>2a7c8f8d-cba9-4c7a-81d5-f6119ef07730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[2]/following::a[2]</value>
      <webElementGuid>eb435f62-b6a8-4c00-aec2-680a94aa8b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrivals'])[1]/preceding::a[1]</value>
      <webElementGuid>b34c7f45-0246-4e2e-8969-99a26e7a14d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='open menu'])[1]/preceding::a[2]</value>
      <webElementGuid>9c38b936-f519-4667-89f0-f3e357a1144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://modern-store.competethemes.com/product-category/denim/')]</value>
      <webElementGuid>a6f90651-441c-47f1-b75a-74d425765416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[4]/a</value>
      <webElementGuid>5d311ed9-de51-43d2-bca8-35a8d2e9a263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://modern-store.competethemes.com/product-category/denim/' and (text() = 'Denim' or . = 'Denim')]</value>
      <webElementGuid>bd25ac20-f627-40ba-8b06-02ae0ff3c284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
