<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sale_attachment-woocommerce_thumbnail s_4ca265</name>
   <tag></tag>
   <elementGuidId>31b4406d-6f89-4e43-a085-f5ff8b806056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loop-container']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.entry.product.type-product.post-317.status-publish.instock.product_cat-denim.product_cat-women.has-post-thumbnail.sale.featured.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02902e7a-36b8-4b56-927f-9a7662483aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b8519545-93ad-44d5-adee-b8c7010848db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>635fb45c-1924-4157-a46a-c1cd748d263a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg</value>
      <webElementGuid>fc949add-782c-4953-b57d-453535ec9e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded</value>
      <webElementGuid>5e5a5c35-14f7-4eba-80e5-42086adc2ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>228ec5ee-ab40-44d0-bf7b-5f903d1f0815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-768x768.jpg 768w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-1024x1024.jpg 1024w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-100x100.jpg 100w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841.jpg 2000w</value>
      <webElementGuid>735591b4-a693-4cd4-9e33-070379aab991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>a14dc634-7eba-4305-8178-87d17a5dd64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg</value>
      <webElementGuid>bf2c6d43-b7b8-4abd-9fd2-e07a5f7a74a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>6ca5f719-6a90-4315-a19e-9228d4c77d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>7699d846-765b-496f-aa42-1bb1f2902cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-768x768.jpg 768w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-1024x1024.jpg 1024w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-100x100.jpg 100w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841.jpg 2000w</value>
      <webElementGuid>530d8c99-95ff-4832-a582-8681d5205524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loop-container&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;entry product type-product post-317 status-publish instock product_cat-denim product_cat-women has-post-thumbnail sale featured shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded&quot;]</value>
      <webElementGuid>1362dae3-93aa-48b0-9749-6b01bd6e25ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>664b3450-5e8c-4f81-bfee-354dd4ceba7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loop-container']/ul/li[2]/a/img</value>
      <webElementGuid>40fa0fa9-f703-40e0-97a8-01cb91b8981c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg')]</value>
      <webElementGuid>895b6b36-a054-48e1-840a-2ec0f71a16c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>df24ea5b-7ee7-4728-b875-27824fc36b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/accessories-adult-attractive-413841-300x300.jpg']</value>
      <webElementGuid>d1eaad71-d230-4741-84f1-0dd12fd16b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/urban-mens-fashion-300x300.jpg')]</value>
      <webElementGuid>7c3325cc-a1c2-43c4-a81d-8b42e9270359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/urban-mens-fashion-300x300.jpg']</value>
      <webElementGuid>020bafcc-8e16-4966-8ef6-d688b03bce22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loop-container']/ul/li/a/img</value>
      <webElementGuid>4e7b1565-d03b-4e69-907b-4976e8be16cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/woman-blue-300x300.jpg')]</value>
      <webElementGuid>74cb28a9-6009-4347-84bb-2a225c71b1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>b2a6bc03-dfb3-4b52-a53d-56028b8ac99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/woman-blue-300x300.jpg']</value>
      <webElementGuid>18dd7596-6057-41c3-9046-656f5fe5bf1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
