<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_691320</name>
   <tag></tag>
   <elementGuidId>ba6a399a-10b1-4b77-8cae-75a9b5513aea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loop-container']/ul/li[7]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.entry.product.type-product.post-324.status-publish.instock.product_cat-women.has-post-thumbnail.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b18dda9-ee26-4b75-a769-2fec1ca8039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a0aa8aec-b525-43f0-892c-87900f0ace4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>dda3c136-6d17-482e-b66f-95365262c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg</value>
      <webElementGuid>3b973d95-a4e3-42fb-9159-88444847cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded</value>
      <webElementGuid>4c30b284-19f2-4982-9734-92eb1b21513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ce12600d-cfd2-4163-ba63-fec714aed78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-100x100.jpg 100w</value>
      <webElementGuid>289dc426-f91e-45b7-894f-3456b9973ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>1b1f6558-ba0b-48b4-b27e-1461dee69046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg</value>
      <webElementGuid>b6a7a6a4-da4c-4e4a-a26a-3ec5edb237cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>c56c47c5-3d5c-4e03-b339-cb7227af0691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>0931ab26-988a-4c66-b248-b42d9c4341c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-100x100.jpg 100w</value>
      <webElementGuid>ab729604-b2f7-4134-b543-4f39654244b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loop-container&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;entry product type-product post-324 status-publish instock product_cat-women has-post-thumbnail shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded&quot;]</value>
      <webElementGuid>ad602b32-b85e-4bf6-a617-7c4e27089421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>c587f336-709e-45b3-ae8b-fad19078b06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loop-container']/ul/li[7]/a/img</value>
      <webElementGuid>1ef366d4-c8c1-43c1-b5d1-da7df7d32b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg')]</value>
      <webElementGuid>9989fc71-0cc2-44d1-ba97-65cb3dcf9513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/img</value>
      <webElementGuid>93b0a2f3-e64d-43ab-a093-f4697801dc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-summer-fashion-300x300.jpg']</value>
      <webElementGuid>73f0dcf3-01f4-43b9-bd4d-bf72595c07a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
