<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_5f269b</name>
   <tag></tag>
   <elementGuidId>bdd4a6db-3325-408b-8ffa-7d2e0736a9a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-317']/section/ul/li[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.entry.product.type-product.post-300.status-publish.instock.product_cat-denim.has-post-thumbnail.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9aa1fbf-5c13-4b3b-9506-1215981d8e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>6babb341-c3b4-4881-be11-7b87480b1f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>94b8d431-ef95-4bfb-9219-9d480a8dfdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-300x300.jpg</value>
      <webElementGuid>db22c1fa-3da0-493a-8153-0286f648bcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>ded7d439-2e6a-4137-a14f-40aad9f3c2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ab91d111-3896-4d84-ba6a-13097cb5558b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-100x100.jpg 100w</value>
      <webElementGuid>73ff7b2e-eba6-4289-b08f-d29d2b135027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>796d05e2-f492-4354-9788-ec2a21c6f586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-317&quot;)/section[@class=&quot;related products&quot;]/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;entry product type-product post-300 status-publish instock product_cat-denim has-post-thumbnail shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>a5f492e1-a9f9-40a4-ba26-cd44298c28da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>c96ea119-f8cf-4612-9c9e-1bf05184da09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-317']/section/ul/li[3]/a/img</value>
      <webElementGuid>a1496146-97c4-4f14-a87b-1d88f76be593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-300x300.jpg')]</value>
      <webElementGuid>548a7a96-a131-4687-837f-3204ccfd9ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>6a37ebf5-6497-42d4-93dc-a6a2c8afc67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1831550-300x300.jpg']</value>
      <webElementGuid>19ac1fc3-5f17-492f-9551-7aaaad5d233e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-326']/section/ul/li[2]/a/img</value>
      <webElementGuid>e56d2af3-dad5-487b-8211-95bf5882f47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/blur-boy-depth-of-field-1183266-300x300.jpg')]</value>
      <webElementGuid>bc28d633-8560-4312-99d1-4838f1fd09d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>7d49cce6-a2d8-4921-a202-c4599a923b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/blur-boy-depth-of-field-1183266-300x300.jpg']</value>
      <webElementGuid>9ca75a99-b1a3-4fec-ac0f-c51a3bdad2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
