<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_White Skinny Tapered Jeans quantity_quantity</name>
   <tag></tag>
   <elementGuidId>48140b3d-27c8-4181-b81e-bee396cc2e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_64b8c80480dfb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity_64b8c80480dfb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74805e28-d444-4988-9806-50416ceba897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>66ffe993-f190-4fab-95d2-8cdadf795d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_64b8c80480dfb</value>
      <webElementGuid>ad676c8f-61d8-49c6-8b3e-ad26cf4c3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>34d45513-966f-48e8-b6f1-9887069b7c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>20423b77-c01e-478f-82fd-07ff48dc0bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dcc0f184-4ae1-4069-bf34-742c536f04e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>3f38b0e7-9b54-4f58-ae6a-e80db4e8b963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>766a70af-67bc-4f90-b83c-d8fbc888853c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>817a4788-b3e6-4f2e-b6d1-1c70545c11ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b099c5ba-8b44-4f6d-b881-b60680574be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>0032aa2c-1d0d-4d19-92ab-8ff51afffb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e61a2232-3600-4b22-b974-94092d7409b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_64b8c80480dfb&quot;)</value>
      <webElementGuid>66675203-4916-408c-95c7-6f80ae181769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>97b7ee8a-c2a6-44b9-ab4e-99f599f4ef20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_64b8c80480dfb']</value>
      <webElementGuid>3eddeb48-ddba-46ae-b613-14ae96122b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-317']/div[2]/form/div/input</value>
      <webElementGuid>aac6c582-de48-4eed-aa82-16a5eafb55e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/form/div/input</value>
      <webElementGuid>cf9dec2d-f675-4cac-abaa-a9914d77d807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_64b8c80480dfb' and @name = 'quantity' and @title = 'Qty']</value>
      <webElementGuid>04d946b8-4fa0-4b2e-98e5-e7432666505a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
